version: "3"
services:
  uwsgi:
    build:
      context: .
    container_name: sti_uwsgi
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./:/app
    environment:
      FLASK_APP: messenger
      STI_MSN_DB: mysql+pymysql://sti:stipass@sti_db/sti

  db:
    image: mariadb/server
    container_name: sti_db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: sti
      MYSQL_ROOT_PASSWORD: stipass
      MYSQL_PASSWORD: stipass
      MYSQL_DATABASE: sti

  adminer:
    image: adminer
    container_name: sti_adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: sti_db
    depends_on:
      - db
